# Generated by Django 5.2.5 on 2025-09-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_details/')),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
