# Generated by Django 5.2.5 on 2025-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_you_may_also_like',
            field=models.BooleanField(default=False),
        ),
    ]
